import os
import logging
from telegram import Update
from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler, MessageHandler, filters
from dotenv import load_dotenv
from . import database as db
from . import triage
from . import support_bridge
from . import frontier_logic

# ... (existing imports)

# ... (existing code) ...

async def broadcast_frontier_summary(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Generates a daily debrief of the biggest busts and pushes a 'NotebookLM Studio' link.
    Triggered by /debrief.
    """
    import time
    
    # Mocking the Studio Link generation
    studio_link = f"https://notebooklm.google.com/studio/frontier_debrief_{int(time.time())}"
    
    # Fetch recent busts for context (Mock if empty)
    bounties = frontier_logic.get_recent_bounties(limit=3)
    
    bust_list = ""
    for b in bounties:
        bust_list += f"• `{b['target'][:10]}...` (Payout: {b['payout_eth']} ETH)\n"
        
    if not bust_list:
        bust_list = "(No major busts today)"

    msg = (
        "🎙️ *Frontier Daily Debrief* 🎙️\n\n"
        "The Neural Bridge has analyzed today's top bounties.\n"
        f"{bust_list}\n"
        "Listen to the AI-generated audio overview of the biggest exploits:\n\n"
        f"🎧 [Play Audio Briefing]({studio_link})\n\n"
        "_Generated by NotebookLM Studio_"
    )
    
    await update.message.reply_text(msg, parse_mode="Markdown")

if __name__ == '__main__':
    # ...
    application = ApplicationBuilder().token(os.getenv("BOT_TOKEN")).build()
    
    async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
        await context.bot.send_message(chat_id=update.effective_chat.id, text="🛡️ **Vera-Verify Active**\nSecure communication channel established.")

    async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
        await context.bot.send_message(chat_id=update.effective_chat.id, text="Commands:\n/link <OTP> - Link Account\n/explain <ADDR> - AI Audit\n/daily - Sheriff Briefing\n/debrief - NotebookLM Studio")

    async def link_account(update: Update, context: ContextTypes.DEFAULT_TYPE):
        if not context.args:
            await update.message.reply_text("Usage: /link <OTP_CODE>")
            return
        otp = context.args[0].strip().upper()
        telegram_id = str(update.effective_user.id)
        success, result = db.verify_and_link_telegram(otp, telegram_id)
        if success:
            await update.message.reply_text(f"✅ Account Linked! User ID: `{result}`", parse_mode='Markdown')
        else:
            await update.message.reply_text(f"❌ Link Failed: {result}")

    async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
        text = update.message.text
        # Simple Triage Logic
        if len(text) == 42 and text.startswith("0x"):
            # It's an address, run fast triage
            await update.message.reply_text(f"🔍 Analyzing Contract: `{text}`...", parse_mode='Markdown')
            report_id, score, risk = triage.fast_scan(text)
            emoji = "🟢" if score > 80 else "🔴"
            await update.message.reply_text(f"{emoji} **Triage Complete**\nVeraScore: {score}/100\nRisk: {risk}\n[View Ledger](https://veraguard.app/ledger/{report_id})", parse_mode='Markdown')
        else:
            await update.message.reply_text("Send a Contract Address (0x...) for instant triage.")

    application.add_handler(CommandHandler('start', start))
    application.add_handler(CommandHandler('help', help_command))
    application.add_handler(CommandHandler('link', link_account))
    application.add_handler(CommandHandler('explain', explain_command))
    application.add_handler(CommandHandler('revenue', revenue_command)) 
    application.add_handler(CommandHandler('daily', daily_briefing))
    application.add_handler(CommandHandler('debrief', broadcast_frontier_summary)) # [NEW]
    application.add_handler(MessageHandler(filters.TEXT & (~filters.COMMAND), handle_message))
    
    print("🤖 Vera-Verify Bot Polling...")
    application.run_polling()
